full_name:Trivia Kata

# set your preferred editor and diff tool.
view_program:subl
diff_program:diff

# Settings for the Python version
executable:${TEXTTEST_HOME}/python/texttest_fixture.py
interpreter:python3

# Settings for the C++ version
#executable:${TEXTTEST_HOME}/C++/build/Trivia

# Settings for the C version
#executable:${TEXTTEST_HOME}/C/build/trivia

filename_convention_scheme:standard
